# Copyright (c) 2023 Paul Barker <paul@pbarker.dev>
# SPDX-License-Identifier: Apache-2.0

name: Build website
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Set up caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.local/pipx
          key: ${{ runner.os }}-cache

      - name: Install poetry
        run: pipx install poetry==1.8.2

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Install Tailwind CSS
        run: |
          wget "https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.1/tailwindcss-linux-x64" -O /usr/local/bin/tailwindcss
          chmod a+x /usr/local/bin/tailwindcss

      - name: Build website with Pelican & TailwindCSS
        run: |
          poetry run pelican
          tailwindcss -i css/base.scss -o public/css/main.css

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: public

  deploy:
    name: Deploy
    needs: build
    if: github.repository == 'unnecessary-abstraction/pbarker.dev'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: public
          path: public

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: pbarker
          directory: public
          branch: ${{ github.ref_name }}
